Tests for resend_otp_api
ECellNitrr/ecell-main-server pull request #44
Opened 2021-02-13 07:56 UTC by akhil-maker

### Fixes #39 

### Description
Adding tests for resend_otp api.

**Type of Change:** (Delete irrelevant options)
- Code
- Testing

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested locally.

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-02-14 13:32 UTC, anshsrtv requested changes
Great job 🔥🚀  @akhil-maker 

- I would suggest, if you are using docstrings, write them after the function declaration. Read more about them [here](https://www.geeksforgeeks.org/python-docstrings/). 
- Also, you can import and make use of `AuthAPITestCase` to create an auth client.

2021-02-15 17:25 UTC, akhil-maker commented
@anshsrtv and @priyanshisharma  please give your reviews.

2021-02-15 17:52 UTC, anshsrtv approved these changes

2021-02-15 20:15 UTC, priyanshisharma approved these changes
Looks right to me! 🚀

2021-02-15 20:15 UTC, merged